{
  "name": "UGM Data Warehouse Devcontainer",
  "dockerComposeFile": "docker-compose.yml",
  "service": "devcontainer",
  "workspaceFolder": "/workspace",
  
  "remoteEnv": {
    "AIRFLOW_HOME": "/workspace/airflow"
  },

  "customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python",
        "Binnford.dbt-formatter",
        "innoverio.vscode-dbt-power-user",
        "mtxr.sqltools",
        "mtxr.sqltools-driver-pg"
      ]
    }
  },
  
  "postCreateCommand": "mkdir -p /workspace/airflow /workspace/data && psql postgres://ugm_user:ugm_password@localhost:5432/procurement_dw -c 'CREATE SCHEMA IF NOT EXISTS raw; CREATE SCHEMA IF NOT EXISTS analytics;' && airflow db init && airflow users create --username admin --firstname UGM --lastname Mahasiswa --role Admin --email mhs@mail.ugm.ac.id --password admin",

  // Tambahkan baris ini untuk otomatisasi setiap startup:
  "postStartCommand": "airflow webserver -D && airflow scheduler -D",

  "forwardPorts": [8080, 5432],
  "remoteUser": "vscode"
}
